apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application
  namespace: kasadara
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-application
  template:
    metadata:
      labels:
        app: python-application
    spec:
      containers:
        - name: python-application
          image: ghcr.io/softwarestacksolutions/python-application:latest
          ports:
            - containerPort: 8000  # Match this to your app's actual port
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: db-config     # Inject DB config (DB_USER, DB_NAME, DB_HOST)
            - secretRef:
                name: db-secret     # Inject DB_PASSWORD
      imagePullSecrets:
        - name: ghcr-secret         # For pulling from GitHub Container Registry
