name: python CI/CD pipeline

on:
 push:
    branches: [development, main]
 pull_request:
    branches: [development]
    
 workflow_dispatch:

permissions:
  contents: write
  packages: write
  pull-requests: write
  security-events: write
  actions: read

jobs:

  codeql-scan:
    name: CodeQL Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  testing:
    name: Run Unit Tests and Pytest
    runs-on: ubuntu-latest
    needs: codeql-scan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run unittest
        run: python -m unittest discover -s tests

      - name: Run pytest
        run: |
          export PYTHONPATH="$PYTHONPATH:$(pwd)"
          pytest tests --junitxml=pytest-report.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: pytest-report.xml

  build-and-publish-artifact:
    name: Build and Publish Artifact Package
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build Package
        run: |
          pip install build
          python -m build --sdist --wheel --outdir dist/
          cd dist && zip -r ../python-package.zip .

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: python-package.zip

      - name: Checkout Artifact Repo
        uses: actions/checkout@v4
        with:
          repository: SoftwareStackSolutions/Artifact_Storage
          ref: main
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: Artifact_Storage

      - name: Push Zipped Artifact with Versioning
        run: |
          mkdir -p Artifact_Storage/Backend_Artifact
          version=v$(date +%Y%m%d%H%M%S)
          cp python-package.zip Artifact_Storage
